version: '3.4'

networks:
  backend:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local

services:
  bbdd:
    container_name: dbContainer
    image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-20.04  
    ports:
      - "1433:1433"  
    networks:
      - backend
    volumes:
      - sqlserver-data:/var/opt/mssql 
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "G#tL9wX3r!sPzD7b"  

  api:
    container_name: apiContainer
    image: reto2_api:1.0  
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "4444:80" 
    networks:
      - backend
    depends_on:
      - bbdd 
    environment:
      ConnectionStrings__DefaultConnection: "Server=dbContainer,1433;Database=VideojuegosDB;User Id=sa;Password=G#tL9wX3r!sPzD7b;TrustServerCertificate=True"

