version: '3.4'

networks:
  backend:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local

services:
  #bbdd:
   # container_name: dbContainer
    #image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-20.04 
   # ports:
  #    - "1433:1433"  
   # networks:
   #   - backend
   # volumes:
  #    - sqlserver-data:/var/opt/mssql 
   # environment:
   #   ACCEPT_EULA: "Y"
   #   MSSQL_SA_PASSWORD: "G#tL9wX3r!sPzD7b"
 #   healthcheck:
 #     test: ["CMD", "bash", "-c", "until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'G#tL9wX3r!sPzD7b' -Q 'SELECT 1' &>/dev/null; do sleep 1; done"]
  #    interval: 10s
  #    retries: 5
  #    start_period: 10s

  api:
    container_name: apiContainer
    image: bydaniel1111/docker-backend-deployement:04  
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "4444:80" 
    networks:
      - backend
   # depends_on:
   #   bbdd:
    #    condition: service_healthy
    environment:
      ASPNETCORE_HTTP_PORTS: "80"
      ConnectionStrings__VideojuegosDB: "Server=videojuegosdb.cuyuzjknbjfe.us-east-1.rds.amazonaws.com,1433;Database=VideojuegosDB;User Id=sa;Password=G#tL9wX3r!sPzD7b;TrustServerCertificate=True"
